### ISSUE TITLE
home-manager: 'Filesystem "FUSE" not supported' error with Dropbox

### ISSUE THREAD

**Issue by bbigras** [nix-community/impermanence#33]
I'm using 2cda5cd30bc7c56240a1a91ec8d44c6d5222ee17

I was using:

```nix
    home.persistence."/persist/home/bbigras" = {
      directories = [
        ".dropbox-dist"
        ".dropbox-hm"
      ];
```

switching them to `environment.persistence."/persist".directories` seems to work.

journalctl
```
déc 29 17:28:24 laptop vsbgld509hg85p3lblwxzcfmj6wvm18x-dropbox-start[30035]: Impossible de d\xe9marrer Dropbox.
déc 29 17:28:24 laptop vsbgld509hg85p3lblwxzcfmj6wvm18x-dropbox-start[30035]: Une erreur d'autorisation est g\xe9n\xe9ralement \xe0 l'origine de ce probl\xe8me. Une erreur p>
déc 29 17:28:24 laptop vsbgld509hg85p3lblwxzcfmj6wvm18x-dropbox-start[30035]: Pour obtenir une aide suppl\xe9mentaire, consultez https://www.dropbox.com/c/help/permissions_e>
déc 29 17:28:24 laptop vsbgld509hg85p3lblwxzcfmj6wvm18x-dropbox-start[30035]: Veuillez contacter l'assistance Dropbox et indiquer les informations suivantes pour obtenir de >
déc 29 17:28:24 laptop vsbgld509hg85p3lblwxzcfmj6wvm18x-dropbox-start[30035]: /tmp/dropbox_error1l3ed21w.txt
```

error file
```
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 806, in wrapper
  File "dropbox/client/main.pyc", line 6595, in finish_dropbox_boot
  File "dropbox/client/main.pyc", line 6060, in _init_components_for_account
  File "dropbox/client/main.pyc", line 5999, in create_sync_engine
  File "dropbox/sync_engine_boundary/factory.pyc", line 261, in make_sync_engine
  File "dropbox/sync_engine/nucleus/classic_client/sync_engine.pyc", line 340, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/modern_client/modern_client.pyc", line 158, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/modern_client/base.pyc", line 155, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 222, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 602, in _init_new_engine_locked
  File "dropbox/sync_engine/nucleus/thin_client/client.pyc", line 217, in __init__
  File "extensions/nucleus/nucleus_python.pyx", line 88, in nucleus_python.NucleusSyncEngine.__cinit__
nucleus_python.SyncEngineError: "Initializing engine |>> Initializing platform |>> Checking if filesystem is supported |>> Filesystem \"FUSE\" not supported! See dropbox.com>
(END)
```

**Comment by talyz** [comment]
Dropbox has some filesystem checks in place and only allows a few specific file systems for the `Dropbox` directory, the `.dropbox` and `.dropbox-dist` ones should be fine, though. I've solved this by pointing Dropbox to the real directory instead, i.e. `/persistence/home/talyz/Dropbox`. I'm not using the `home-manager` Dropbox module, though.
